config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  get 'slogan' => 'welcome#slogan'
  get 'about' => 'welcome#about'
  
  resources :menus, only: [:index]
  
  namespace :menus do
    resources :lunch,  only: [:index]
    resources :dinner, only: [:index]
  end

end

app/models/hot_cold_sandwiches_calzone_pasta_salad_dinner_config.rb
require 'yaml'
class HotColdSandwichesCalzonePastaSaladDinnerConfig
    def self.current_menu
        current_menu = load_menu
    end
    def self.load_menu
         YAML.load(File.read("#{Rails.root.to_s}/config/hot_cold_sandwiches_calzone_pasta_salad_dinner.yml"))
    end
end

app/models/lunch_menu_config.rb
require 'yaml'
class LunchMenuConfig
    def self.current_menu
        current_menu = load_menu
    end
    def self.load_menu
         YAML.load(File.read("#{Rails.root.to_s}/config/lunch_menu.yml"))
    end
end

app/models/pizza_dinner_config.rb
require 'yaml'
class PizzaDinnerConfig
    def self.current_menu
        current_menu = load_menu
    end
    def self.load_menu
         YAML.load(File.read("#{Rails.root.to_s}/config/pizza_dinner.yml"))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/menus/dinner_controller.rb
module Menus
    class DinnerController < ApplicationController
      def index
        
      end
    end
end 

app/controllers/concerns/menus/lunch_controller.rb
module Menus
    class LunchController < ApplicationController
      def index
      end
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
   
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def slogan
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinner_helper.rb
module DinnerHelper
end

app/helpers/lunch_helper.rb
module LunchHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application' , media: "all",'data-turbolinks-track' => true%> 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, :cache => true ,:defer=> "defer",:recursive => true %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyB_bhcuJbmnYHQViWNhZopT9QHxWcUjpT0', :cache => true , :defer=> "defer" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">   
  
</head>
<body data-spy="scroll" data-target=".icon-list" data-offset="450">
  <%= render 'shared/menu'  %>
  <div class="col-md-12" style="height:9vh;color:red;"></div>
  <%= render template: '/welcome/slogan'    if controller.controller_name == 'welcome'%>
  <%= render template: '/welcome/about'     if controller.controller_name =='welcome'%>
  <%= render template: '/menus/index'       if controller.controller_name == 'welcome' || controller.controller_name == 'menus'%>
  <%= render template: 'menus/lunch/index'  if controller.controller_name == 'lunch'%>
  <%= render template: 'menus/dinner/index' if controller.controller_name == 'dinner'%>
  <%= render 'shared/contact' %>
  <script>
    // new WOW().init();
  </script>
</body>
</html>

app/views/menus/dinner/index.html.erb
<div class="jumbotron" style=" margin:20px; margin-top:15%; border-radius:5px">
   <div class="row">
       <h2>Dinner Menu</h2>
   </div>
  <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
                <h1 class="text-center"   style="color:red;"> PIZZA</h1>
                <div class ="text-center" style="border: 1px solid red; color: #fff; background: red;">
                    <h2>BUY 1 GET 1 FREE </h2>
                </div>
                <div class="top">
                    <h2 style="color: green; margin-top: 25px; padding: 25px;border: 1px solid red; background:red;">TOPPINGS: 
                     <span style="color: gray;float:right;">v</span>
                    </h2>
                </div>
                <div class="bottom" style="display:none;">
                    <p style="color: red; font-weight: 700">
                        Pepperoni, Italian Sausage, Chicken, Mushrooms, Onions, Bell Peppers, 
                        Candian Bacon, Black Olives, Meatballs, Ham, Pineapple, Jalapenos,
                        Salami, Anchovies, Fresh Tomatoes, Fresh Garlic, Roasted Garlic, 
                        Cilantro, Grilled Eggplant, Grilled Zucchini, Red Onion, Roasted Peppers
                        , Capers, Sun-dried Tomatoes, Feta Cheese, Artichoke Hearts
                    </p>
                </div>
                
                 <div style="text-align: right; color:green; font-weight: 500;margin-bottom: 19px;">
                   SMALL(2)&nbsp;&nbsp;MEDIUM(2)&nbsp;&nbsp;LARGE(2)
                </div>
                <div class="box" id="topping-pizza">
                      <% PizzaDinnerConfig.current_menu.each do |item,content| %> 
                          <% content.each do |subject,detail| %>
                            <div  class="top" style="text-align: left;">
                                <span style=" display: inline-block;">
                                    <%= subject["name"] %>
                                </span>
                                <span style="float:right; color: red;">
                                    <% subject["price"].each do |p| %>
                                        <%= p %>&nbsp;&nbsp; 
                                    <%end%>  
                                    <span style="color: gray;text-align:right;">v</span>
                                </span> 
                                <span>
                                <%= tag(:br) %>
                                </span>
                             </div>   
                             <% unless subject["ingredients"].nil?  %>
                                 <div class="bottom">
                                    <%= subject["ingredients"]%>
                                 </div>
                             <%end%>
                           <%end%>
                     <%end%>
                 </div>
        </div>
  </div>
   <div class="row"> 
        <form id='form' class="col-xs-12 col-md-12 box" >            
              <% HotColdSandwichesCalzonePastaSaladDinnerConfig.current_menu.each do |item,content| %> 
                <div class="top">
                    <%=item%>
                    <span class="pull-right" style="color: gray;">v</span>
                </div>
                <div class="bottom" >
                     <div class="well">
                  <% content.each do |subject,detail| %>
                   <input type="checkbox" name="menItems" onclick="myFunction(this)" 
            value="<%= subject["name"] %>&nbsp;&nbsp;&nbsp;&nbsp;<%= subject["price"] %>">
                        <span class="box-nip">
                            <%= subject["name"] %>
                        </span>
                        <br>
                        <% unless subject["ingredients"].nil?  %>
                            <%= subject["ingredients"]%>
                            <%= tag(:br) %>
                        <%end%>
                        <%= number_to_currency(subject["price"]) %><br>
                   <%end%>
                   </div>
                </div>
                 <%end%>  
          </form>  
     </div>

 </div> 

 

app/views/menus/index.html.erb
<div id="foodMenu" class="container-fluid" >
    <h1 class="text-center wow fadeIn" data-wow-delay="0.9s"  style="padding-top:15vh">Menu</h1>
    <div class="row">
        <div class="col-sm-6"  >
            <div class="text-center wow fadeIn" data-wow-delay="1.0s" >
                <%= link_to menus_lunch_index_path do %>
                  <%= image_tag "/assets/lunch.logo.png", id: "lunch-logo" %>
                <% end %>
            </div> 
        </div>
        <div class="col-sm-6" >
            <div class="text-center wow fadeIn" data-wow-delay="1.0s" > 
                 <%= link_to menus_dinner_index_path do %>
                  <%= image_tag "/assets/dinner.logo.png", id: "dinner-logo" %>
                <% end %>
            </div>  
        </div>
    </div>
</div>

app/views/menus/lunch/index.html.erb
<div class="jumbotron" style="margin:20px; margin-top:15%; border-radius:5px">
    <div class="row" style=" margin: 0 auto;"> 
        <form id='form' class="col-xs-12 col-md-12 box" >
            <h2>Daily Lunch</h2>
              <% LunchMenuConfig.current_menu.each do |item,content| %> 
                <div class="top">
                    <%=item%>
                    <span class="pull-right" style="color: gray;">v</span>
                </div>
                <div class="bottom" >
                     <div class="well">
                  <% content.each do |subject,detail| %>
                   <input type="checkbox" name="menItems" onclick="myFunction(this)" 
            value="<%= subject["name"] %>&nbsp;&nbsp;&nbsp;&nbsp;<%= subject["price"] %>">
                        <span class="box-nip">
                            <%= subject["name"] %>
                        </span>
                        <br>
                        <% unless subject["ingredients"].nil?  %>
                            <%= subject["ingredients"]%>
                            <%= tag(:br) %>
                        <%end%>
                        <%= number_to_currency(subject["price"]) %><br>
                   <%end%>
                   </div>
                </div>
                 <%end%>  
          </form>  
     </div>
 </div> 

app/views/shared/_contact.html.erb
<style>

</style>

<div id="contact" class="container-fluid"  >
    <div class="jumbotron text-center" id="jumbo-contact1">
        <div class="row">
            <div class="col-md-12 ">
                <h1 class="text-center wow fadeIn" data-wow-delay="0.9s">Contact Us</h1>
            </div>
        </div>
        <div class="row ">
            <div class="col-md-12" style="padding-top: 25px;" >
                <div >
                    <%=fa_icon "phone 4x"%><br>
                    <%= number_to_phone 3106596171 %> <br> 
                </div>
                <div >
                    <%= fa_icon 'envelope 4x' %><br>
                    9030 Venice Blvd, Culver City, CA 90232<br>
                </div>
                <div >
                    <%= fa_icon 'clock-o 4x'%>
                     <div id="myDiv"></div>
                </div>
            </div> 
            <div class="col-md-12"  >
                 <br>
                 <%= fa_icon 'map 4x', style: 'padding-bottom: 15px;' %>
                 <br>
                <!--<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52895.11493642426!2d-118.4547317416587!3d34.045290035451906!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2b98096ce1d1d%3A0x194fad307470a12c!2sLucia&#39;s+Pizza!5e0!3m2!1sen!2sus!4v1499902634600" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>-->
               <div id="gmap" style="width:100%; height: 400px"></div>
            </div>
        </div>
    </div>
    
</div>

app/views/shared/_menu.html.erb
<header id="menu">
    <!-- Navigation --> 
    <div class="navbar-pos">
    	<div class="_3navbar">
    		<div class="menu-wrap">
    			<nav class="menu">
    			    </br> 
    			    <div id='menu-link' class="icon-list">
        			    <a id='menu-logo' href="<%= slogan_path(anchor: 'slogan')%>"> 
        			           <i class="fa fa-pie-chart"></i>
        			           <span style="font-size:1.1em">Lucia's Pizza</span> 
        			    </a>     				
    				    <a  class="scroll" href="<%= slogan_path(anchor: 'slogan')%>">
    				        <i class="fa fa-home"></i>
    				        <span>Home</span>
    				    </a>
    					<a  class="scroll" href="<%= about_path(anchor: 'about')%>">
    					    <i class="fa fa-info" style="padding-left: 3px;"></i>
    					    <span style="padding-left: 3px;">About</span>
    					</a>
    					<a  class="scroll" href="<%= menus_path(anchor: 'foodMenu')%>">
    					    <i class="fa fa-cutlery"></i>
    					    <span>Food</span>
    					</a>
    					<a  class="scroll" href="#contact">
    					    <i class="fa fa-phone"></i>
    					    <span>Contact</span>
    					</a>
    				</div> 
    			</nav>
    			<button class="close-button" id="close-button">Close Menu</button>
    			<h4 class="scroll">Deal of the Day</h4>
    		</div>
    		<button class="menu-button" id="open-button">Open Menu</button>
    	</div>
    	<div class="menu-len">
    		<p>MENU</p>
    	</div>
    	<div class="logo-len">
    	        <%= link_to "Lucia's Pizza", nil , class: 'logo', style: 'pointer-events: none;cursor: default;'%>    	</div>
    	<div class="contact-navsec">
    		<p><a class="scroll" href="#contact">
    		    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    		    CONTACT US</a>
    		</p>
    	</div>
    	<div class="clearfix"></div>
    </div>
    <!-- //Navigation -->
</header>    
    
    

app/views/welcome/about.html.erb
<section  class="container-fluid" id="about">
<div class="jumbotron1" id="jumbo-about" > 
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="text-center wow fadeIn" data-wow-delay="0.9s"  style="padding-top:15vh">About Us</h1>
            <div style="font-size:22px">All, We Offer is taste of KINDNESS</div>
            <p style="font-size:20px;">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint voluptate 
                architecto laboriosam odit nobis provident possimus, fugit molestias iste minus
                reiciendis hic vitae harum laudantium pariatur deleniti nesciunt ex sit.
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi perspiciatis, 
            cum sint totam aperiam eius! Totam, cum eum fuga aut, 
            magnam nihil, cumque, numquam repellat ullam nam incidunt eligendi tempora.
            </p>
        </div>
    </div>
</div>
</section>

app/views/welcome/slogan.html.erb
<section class="container-fluid" id="slogan">
  <div class="row">
    <div class="col-sm-12 col-md-12">
        <%#= video_tag(
              ['pizza_brighter.webm', 'pizza_brighter.m4v','pizza_brighter.ogg'],
              id: 'vid', 
              autoplay: true,
              loop: true,
              muted: false,
              poster: 'poster2.webp'
            )
          %>
          <!--<video  id='vid' autoplay muted poster= "poster.webp">-->
          <!--  <source src="/assets/pizza_brighter.webm#t=1,8" type='video/webm;codecs="vp8, vorbis"'>-->
          <!--  <source src="/assets/pizza_brighter.mp4#t=1,8"  type='video/mp4;codecs="avc1.42E01E, mp4a.40.2"' />-->
          <!--  <source src="/assets/pizza_brighter.m4v#t=1,8">-->
          <!--</video>-->
          <!--if u bring back id div has the same style as a below image-->
          <%= image_tag '/assets/1.jpg', style: 'object-fit: cover;width:100%; height:100vh'%>
          <div class="overlay-desc">
            <h3>
              <%= image_tag('/assets/slicePizza.png', size:"40x60", style:'width:40px; height:60px;') %> OR NOT 
              <%= image_tag('/assets/slicePizza.png', size:"40x60", style:'width:40px; height:60px;') %> , THAT IS THE QUESTION?
            </h3>            
            <span style="color:red;font-size:20px;">
               <div>1 LARGE PIZZA</div>
               <div>UP TO 3 TOPPINGS - PICK-UP ONLY</div>
               <div style='font-size: 18px'>
               <%= number_to_currency 9.95%> + tax
               mention coupon when ordering  <span style="color:green;font-size:25px"> 1 PIZZA ONLY</span>
               </div>            
            </span>
            <!--got rid of bootsrap/buttons temporarly -->
            <%= link_to "tel:3108380331" do %>
              <%= content_tag :button, 'Call Now' , class: 'btn-danger'%>
            <%end%> 
          </div>
    </div> 
  </div>
</section>